### ISSUE TITLE
Request: Config Options for Bucket

### ISSUE THREAD

**Issue by stlouisn** [BasiqueEvangelist/SpiritWalker#7]
Would it be possible to add configuration options to enable/disable the leaky buckets?

**Comment by BasiqueEvangelist** [comment]
> Would it be possible to add configuration options to enable/disable the leaky buckets?

You should be able to just remove the recipe with a datapack.
I will probably add a config option that disables it for you, though

**Comment by BasiqueEvangelist** [comment]
Added in [0.1.4+1.20](https://modrinth.com/mod/spirit-walker/version/0.1.4+1.20)
