### ISSUE TITLE
Seems to have corrupted my world after spirit walker effect ended

### ISSUE THREAD

**Issue by LewisJayden316** [BasiqueEvangelist/SpiritWalker#9]
After using the potion and returning to my body, it caused my game to crash, and my game continues to crash every time I attempt to reload into it

https://pastebin.com/HewyGY53

**Comment by LewisJayden316** [comment]
sorry about that, this link should work:
https://pastebin.com/pjKA5Nmd

**Comment by BasiqueEvangelist** [comment]
This seems to be a crash in PotionWarning [here](https://github.com/StillLutto/potion-warning/blob/main/src/main/java/me/lutto/mixin/StatusEffectInstanceMixin.java#L36), could you try temporarily removing that mod and loading the save?

**Comment by LewisJayden316** [comment]
the save isn't important as it was a test, but thanks for that heads up. This did in fact fix it, sorry to have bothered ya, especially when the offending case wasn't really from your mod. Very cool concept and well done execution, cheers!
